import java.util.ArrayList;
public class HabitatSpecific extends Habitat {
public HabitatSpecific(ArrayList<CAppareil> lapp, ArrayList<CEnsAppareil> lens, ArrayList<CScenario> lscen, ArrayList<CInterface> lint, ArrayList<CProgrammation> lprog)
{
super(lapp,lens,lscen,lint,lprog);
}
public void execScenarioNum(int num)
{
 System.out.println( "Execution du scenario "+this.l_scenarios.get(num).getNomScenario()+"... ");
 switch(num) {
 case 5:      
 for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("e1")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.ETEINT)) {  appareil0.appliquer(TypeActionAppareil.ALLUMER);   }  else {  for(CAppareil appareil1 : this.l_appareils){   if (appareil1.getNomAppareil().equals("e1")){ if (appareil1.etatAppareil.equals(TypeEtatAppareil.DEMI)) {  appareil1.appliquer(TypeActionAppareil.ETEINDRE);   }}}} }} for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("e2")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.ALLUME)) {  appareil0.appliquer(TypeActionAppareil.TAMISER);   }}} for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("v1")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.OUVERT)) {  appareil0.appliquer(TypeActionAppareil.FERMER_PARTIEL);   }}} for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("v1")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.FERME)) {  appareil0.appliquer(TypeActionAppareil.OUVRIR_PARTIEL);     System.out.println(" alors ") ;  }  else {  for(CAppareil appareil1 : this.l_appareils){   if (appareil1.getNomAppareil().equals("v1")){ if (appareil1.etatAppareil.equals(TypeEtatAppareil.DEMI)) {  appareil1.appliquer(TypeActionAppareil.FERMER);   }  else {  for(CAppareil appareil : this.l_appareils)   {  if (appareil.getNomAppareil().equals("v1"))     appareil.appliquer(TypeActionAppareil.OUVRIR); }   System.out.println(" sinon ") ;  } }}} }}
break;
 case 4:      
 for(CAppareil appareil0 : this.l_appareils) {  if (appareil0.typeAppareil.equals(TypeAppareil.AUTRE_APPAREIL_TV)) {   appareil0.appliquer(TypeActionAppareil.ALLUMER);  } } this.execScenarioNum(2);  for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("a1")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.ETEINT)) {  appareil0.appliquer(TypeActionAppareil.ALLUMER_PARTIEL);   }}} for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("a1")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.DEMI)) {  appareil0.appliquer(TypeActionAppareil.ALLUMER);   }  else {  for(CAppareil appareil1 : this.l_appareils){   if (appareil1.getNomAppareil().equals("a1")){ if (appareil1.etatAppareil.equals(TypeEtatAppareil.ALLUME)) {  appareil1.appliquer(TypeActionAppareil.ETEINDRE);   }  else {  for(CAppareil appareil : this.l_appareils)   {  if (appareil.getNomAppareil().equals("a2"))     appareil.appliquer(TypeActionAppareil.ALLUMER); } } }}} }} for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("r1")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.ECO)) {  appareil0.appliquer(TypeActionAppareil.ALLUMER);   }}} for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("r1")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.ETEINT)) {  appareil0.appliquer(TypeActionAppareil.ALLUMER_ECO);   }  else {  for(CAppareil appareil1 : this.l_appareils){   if (appareil1.getNomAppareil().equals("r1")){ if (appareil1.etatAppareil.equals(TypeEtatAppareil.ALLUME)) {  appareil1.appliquer(TypeActionAppareil.ETEINDRE);   }  else {   System.out.println(" bip !") ;  } }}} }} for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("fen")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.OUVERT)) {   System.out.println("fenêtre ouverte !") ;  }}} for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("cafe")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.ALLUME)) {  appareil0.appliquer(TypeActionAppareil.ETEINDRE);   }}} for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("cafe")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.ETEINT)) {  appareil0.appliquer(TypeActionAppareil.ALLUMER);   }}}
break;
 case 2:      
 this.execScenarioNum(1);  for(CAppareil appareil : this.l_appareils)   {  if (appareil.getNomAppareil().equals("hf"))     appareil.appliquer(TypeActionAppareil.ALLUMER); } 
break;
 case 3:      
 for(CAppareil appareil0 : this.l_appareils) {  if (appareil0.typeAppareil.equals(TypeAppareil.VOLET)) {   appareil0.appliquer(TypeActionAppareil.FERMER);  } } for(CAppareil appareil0 : this.l_appareils) {  if (appareil0.typeAppareil.equals(TypeAppareil.ECLAIRAGE)) {   appareil0.appliquer(TypeActionAppareil.ETEINDRE);  } } for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("fen")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.FERME)) {  appareil0.appliquer(TypeActionAppareil.ALLUMER);   }  else {   System.out.println( "Attention : la fenêtre  est ouverte !") ;  } }}for(CAppareil appareil0 : this.l_appareils){  if (appareil0.estTypeAutreAppareil())  { appareil0.appliquer(TypeActionAppareil.ETEINDRE);  } }
break;
 case 0:      
 for(CAppareil appareil0 : this.l_appareils) {  if (appareil0.typeAppareil.equals(TypeAppareil.VOLET)) {    for(CAppareil appareil1 : this.l_appareils){   if (appareil1.typeAppareil.equals(TypeAppareil.VOLET)){ if (appareil1.etatAppareil.equals(TypeEtatAppareil.FERME)) {  appareil1.appliquer(TypeActionAppareil.OUVRIR);   }}} } } for(CAppareil appareil : this.l_appareils)   {  if (appareil.getNomAppareil().equals("e1"))     appareil.appliquer(TypeActionAppareil.ETEINDRE); }  for(CAppareil appareil : this.l_appareils)   {  if (appareil.getNomAppareil().equals("cafe"))     appareil.appliquer(TypeActionAppareil.ALLUMER); }  for(CAppareil appareil0 : this.l_appareils){   if (appareil0.getNomAppareil().equals("rad1")){ if (appareil0.etatAppareil.equals(TypeEtatAppareil.ETEINT)) {  appareil0.appliquer(TypeActionAppareil.ALLUMER);   }}} for(CAppareil appareil : this.l_appareils)   {  if (appareil.getNomAppareil().equals("hf"))     appareil.appliquer(TypeActionAppareil.ALLUMER); } 
break;
 case 1:      
 for(CAppareil appareil0 : this.l_appareils) {  if (appareil0.typeAppareil.equals(TypeAppareil.VOLET)) {   appareil0.appliquer(TypeActionAppareil.FERMER);  } }for(CEnsAppareil ensAppareil0 : this.l_ensembles){  if (ensAppareil0.nomEnsAppareil.equals("mon_eclairage_salon")) { for(CAppareil appareil0 : ensAppareil0.lAppareils) appareil0.appliquer(TypeActionAppareil.ALLUMER); } }
break;
default :     
}
}
}
