

public enum TypeAppareil {
ECLAIRAGE, VOLET, FENETRE, CHAUFFAGE, ALARME, 
AUTRE_APPAREIL_CAFE, AUTRE_APPAREIL_TV, AUTRE_APPAREIL_HIFI,  
AUTRE_APPAREIL_VP, AUTRE_APPAREIL_LL, AUTRE_APPAREIL_LV,
AUTRE_APPAREIL_SL, AUTRE_APPAREIL_PORTAIL
}